### ISSUE TITLE
신고하기 기능 구현

### ISSUE THREAD

**Issue by ymym1024** [Travalue/TripStyle-Android#104]
**Description**
신고하기 기능 구현

**TODO**
- [x] trailer 상세 더보기 추가
- [ ] 신고하기 목록 UI 구현
- [ ] 신고하기 popup 구현
- [ ] 신고하기 API 연결

**ETC**
