### ISSUE TITLE
Trailer 상세조회 네트워크 연결 & 기능 수정

### ISSUE THREAD

**Issue by ymym1024** [Travalue/TripStyle-Android#56]
**Description**
Trailer 상세조회 API 연결 & 기능 수정

**TODO**
- [x] 상세조회 View binding 
- [x] 상세조회 API 연결
- [x] 좋아요 API 연결 
- [x] 좋아요 취소 API 연결 

**ETC**
