### ISSUE TITLE
트레일러 디자인 변경

### ISSUE THREAD

**Issue by ymym1024** [Travalue/TripStyle-Android#60]
**Description**
트레일러 전체/상세 디자인 변경

**TODO**
- [x] color.xml primary color, backgroundcolor 변경
- [x] 트레일러 전체화면 디자인 변경
- [x] 트레일러 상세화면 디자인 변경

**ETC**
