### ISSUE TITLE
공유중인 여행지 

### ISSUE THREAD

**Issue by ymym1024** [Travalue/TripStyle-Android#69]
**Description**
공유중인 여행지 UI 변경 / network 연결

**TODO**
- [x] 공유중인 여행지 color 변경
- [x] recyclerview 디자인 수정
- [x] 공유중인 여행지 network 연결

**ETC**
