### ISSUE TITLE
트레블러 API

### ISSUE THREAD

**Issue by blonded99** [Travalue/TripStyle-Android#80]
**Description**
트레블러쪽 모델 생성 및 API 호출하여 서버와 통신
그 과정에서 필요에 따라 기능 및 UI 변경

**TODO**
- [x] 트레블러 메인(지금 핫한 트레블러 조회)
- [x] 트레블러 검색 결과(검색 결과 조회)
- [ ] 에디터 - 카테고리 옵션(내 카테고리 목록 조회, 트레블러 생성)
- [x] 에디터 - 카테고리 추가(카테고리 추가)

**ETC**
내 카테고리 목록 조회는 끝냈고 트레블러 생성은 다음으로 넘김
