### ISSUE TITLE
카테고리 수정

### ISSUE THREAD

**Issue by ymym1024** [Travalue/TripStyle-Android#81]
**Description**
카테고리 수정 UI디자인 변경, 네트워크 연결

**TODO**
- [x] 카테고리 수정 UI 디자인 변경
- [x] 다이얼로그 공통코드 리팩토링 
- [x] 카테고리 수정 API 연결
- [x] 카테고리 삭제 API 연결
- [x] #84

**ETC**
