### ISSUE TITLE
트레블러 코드 리팩토링

### ISSUE THREAD

**Issue by blonded99** [Travalue/TripStyle-Android#89]
**Description**
트레블러쪽 코드 단순 정리 및 청소

**TODO**
- [x] 함수화
- [x] 파일명 변경
- [x] 변수명 변경
- [x] 불필요한 주석, 로그 삭제
- [x] 필요한 주석 추가
- [x] 사용하지 않는 파일 삭제

**ETC**
